export const ROUTE_NAME = 'ROUTE_NAME'
export const CURRENT_ORDER = 'CURRENT_ORDER'
export const NAVIGATION = 'NAVIGATION'
export const CURRENT_ORDER_REQUESTS = 'CURRENT_ORDER_REQUESTS'
export const BLOG_LIST_SHOW = 'BLOG_LIST_SHOW'
export const TODAY_POST_SHOW = 'TODAY_POST_SHOW'
export const TODAY_MEAL_SHOW = 'TODAY_POST_SHOW'

export const ADD_UPDATE_ACTIVITIES = 'ADD_UPDATE_ACTIVITIES'
export const ALL_LIST_ACTIVITIES = 'ALL_LIST_ACTIVITIES'

export const DAILY_ACTIVITY = 'DAILY_ACTIVITY'
export const DAILY_ACTIVITY_TYPE = 'DAILY_ACTIVITY_TYPE'
export const DAILY_ACTIVITY_ACTIVE = 'DAILY_ACTIVITY_ACTIVE'

export const BREAKFAST_DAILY_ACTIVITY = 'BREAKFAST_DAILY_ACTIVITY'
export const BREAKFAST_ACTIVE = 'BREAKFAST_ACTIVE'
export const BREAKFAST_DAILY_RESPONSE = 'BREAKFAST_DAILY_RESPONSE'

export const LUNCH_DAILY_ACTIVITY = 'LUNCH_DAILY_ACTIVITY'
export const LUNCH_ACTIVE = 'LUNCH_ACTIVE'
export const LUNCH_DAILY_RESPONSE = 'LUNCH_DAILY_RESPONSE'

export const DINNER_DAILY_ACTIVITY = 'DINNER_DAILY_ACTIVITY'
export const DINNER_ACTIVE = 'DINNER_ACTIVE'
export const DINNER_DAILY_RESPONSE = 'DINNER_DAILY_RESPONSE'

export const SNACK_DAILY_ACTIVITY = 'SNACK_DAILY_ACTIVITY'
export const SNACK_ACTIVE = 'SNACK_ACTIVE'
export const SNACK_DAILY_RESPONSE = 'SNACK_DAILY_RESPONSE'

export const ADD_UPDATE_CUSTOM_RECIPE = 'ADD_UPDATE_CUSTOM_RECIPE'
export const UPDATE_CUSTOM_RECIPE = 'UPDATE_CUSTOM_RECIPE'
export const DELETE_CUSTOM_RECIPE = 'DELETE_CUSTOM_RECIPE'

export const CUSTOM_BREAKFAST_ACTIVE = 'CUSTOM_BREAKFAST_ACTIVE'
export const CUSTOM_BREAKFAST_DAILY_RESPONSE = 'CUSTOM_BREAKFAST_DAILY_RESPONSE'

export const CUSTOM_LUNCH_ACTIVE = 'CUSTOM_LUNCH_ACTIVE'
export const CUSTOM_LUNCH_DAILY_RESPONSE = 'CUSTOM_LUNCH_DAILY_RESPONSE'

export const CUSTOM_DINNER_ACTIVE = 'CUSTOM_DINNER_ACTIVE'
export const CUSTOM_DINNER_DAILY_RESPONSE = 'CUSTOM_DINNER_DAILY_RESPONSE'

export const CUSTOM_SNACK_ACTIVE = 'CUSTOM_SNACK_ACTIVE'
export const CUSTOM_SNACK_DAILY_RESPONSE = 'CUSTOM_SNACK_DAILY_RESPONSE'

export const PRODUCT_BREAKFAST_ACTIVE = 'PRODUCT_BREAKFAST_ACTIVE'
export const PRODUCT_BREAKFAST_ACTIVE_RESPONSE = 'PRODUCT_BREAKFAST_ACTIVE_RESPONSE'
export const PRODUCT_BREAKFAST_ACTIVE_DATA = 'PRODUCT_BREAKFAST_ACTIVE_DATA'

export const PRODUCT_LUNCH_ACTIVE = 'PRODUCT_LUNCH_ACTIVE'
export const PRODUCT_LUNCH_ACTIVE_RESPONSE = 'PRODUCT_LUNCH_ACTIVE_RESPONSE'
export const PRODUCT_LUNCH_ACTIVE_DATA = 'PRODUCT_LUNCH_ACTIVE_DATA'


export const PRODUCT_DINNER_ACTIVE = 'PRODUCT_DINNER_ACTIVE'
export const PRODUCT_DINNER_ACTIVE_RESPONSE = 'PRODUCT_DINNER_ACTIVE_RESPONSE'
export const PRODUCT_DINNER_ACTIVE_DATA = 'PRODUCT_DINNER_ACTIVE_DATA'


export const PRODUCT_SNACK_ACTIVE = 'PRODUCT_SNACK_ACTIVE'
export const PRODUCT_SNACK_ACTIVE_RESPONSE = 'PRODUCT_SNACK_ACTIVE_RESPONSE'
export const PRODUCT_SNACK_ACTIVE_DATA = 'PRODUCT_SNACK_ACTIVE_DATA'

/////// Product Total Calories
export const BREAKFAST_CALORIES = 'BREAKFAST_CALORIES'
export const LUNCH_CALORIES = 'LUNCH_CALORIES'
export const DINNER_CALORIES = 'DINNER_CALORIES'
export const SNACK_CALORIES = 'SNACK_CALORIES'
/////// Product category
export const SNACK_PRODUCT = 'SNACK_PRODUCT'
export const BREAKFAST_PRODUCT = 'BREAKFAST_PRODUCT'
export const LUNCH_PRODUCT = 'LUNCH_PRODUCT'
export const DINNER_PRODUCT = 'DINNER_PRODUCT'




