import { StyleSheet, Dimensions, Platform } from 'react-native';
import Responsive from 'react-native-lightweight-responsive';
import Colors from '../../../Theme/Colors';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

const WIDTH = Dimensions.get('window').width;
const HEIGHT = Dimensions.get('window').height;
const APPLE_GREEN = '#7AD319';

const { width, height } = Dimensions.get('window');
export const styles = StyleSheet.create({
  mainLayout: {
    flex: 1,
    backgroundColor: '#ffffff',
    flexDirection: 'column',
  },
  infoName: {
    marginLeft: Responsive.width(5),
    color: '#000',
    fontWeight: '500',
    fontSize: hp('1.9%'),
    letterSpacing: 1,
  },
  carbsText: {
    color: '#000',
    fontSize: 13,
    fontWeight: '300',
    margin: '2%',
    textAlign: 'center',
  },
  infoTextName: {
    color: '#9E9F9D',
    fontSize: hp('1.3%'),
    fontWeight: '300',
    margin: '1.5%',
  },
  section: {
    paddingLeft: Responsive.width(10),
    paddingRight: Responsive.width(20),
    paddingBottom: Responsive.width(20),
    //  borderBottomWidth: 6.5,
    shadowColor: 'red',
    borderBottomColor: '#cccccc',
    shadowOpacity: Platform.OS === 'android' ? 0.5 : 0,
  },
  headerStyle: {
    flexDirection: 'row',
    marginTop: Platform.OS == 'ios' ? '14%' : '8%',
    marginBottom: Platform.OS == 'ios' ? '3%' : '2%',
    backgroundColor: '#ffffff',
  },
  header: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: '#03A9F4',
    overflow: 'hidden',
  },
  bar: {
    marginTop: 28,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    backgroundColor: 'transparent',
    color: 'white',
    fontSize: hp('1.6%'),
  },
  headerText: {
    marginLeft: 10,
    color: '#000',
    fontSize: hp('2.5%'),
    fontWeight: '400',
  },
  tipText: {
    marginBottom: 5,
    color: '#000',
    fontSize: hp('1.6%'),
    fontWeight: '400',
  },
  tipSubText: {
    marginBottom: 10,
    color: 'rgba(0,0,0,0.6)',
    fontSize: hp('1.1%'),
    fontWeight: '400',
  },
  tipMoreText: {
    marginBottom: 5,
    color: Colors.green,
    fontSize: hp('1.1%'),
    fontWeight: '400',
  },
  headerDateText: {
    color: Colors.green,
    fontSize: hp('1.2%'),
    fontWeight: '400',
  },
  feedText: {
    marginLeft: Responsive.width(20),
    marginTop: Responsive.height(20),
    color: '#000',
    fontSize: hp('1.3%'),
    fontWeight: '400',
  },
  itemShortText: {
    marginLeft: Responsive.width(20),
    marginTop: Responsive.height(20),
    color: '#000',
    fontSize: hp('1.6%'),
    fontWeight: '400',
  },
  feedTitleText: {
    marginLeft: Responsive.width(20),
    marginTop: Responsive.height(10),
    color: '#000',
    fontSize: hp('1.6%'),
    fontWeight: '300',
  },
  feedSubTitleText: {
    marginTop: Responsive.height(5),
    marginLeft: Responsive.width(20),
    color: '#9E9F9D',
    fontSize: hp('1.6%'),
    marginBottom: 10,
    fontWeight: '300',
  },
  feedReadTimeText: {
    marginTop: Responsive.height(5),
    color: '#9E9F9D',
    fontSize: hp('1.6%'),
    marginBottom: 10,
    fontWeight: '300',
  },
  headerGoalStyle: {
    marginTop: '2%',
  },
  // gender:{
  //   marginHorizontal:10,
  //   margin:8,
  //   height:120,
  //   width:120,
  //   alignItems:"center",
  //   padding:8,
  //   backgroundColor:'#ffffff',
  //   shadowColor: '#D8D8D8',
  //   shadowOpacity: 1,
  //   shadowRadius: 5,
  //   borderRadius:7,
  //   elevation:10,
  //   borderStyle:"solid",
  //   borderWidth:1,
  //   borderColor:'#D8D8D8',
  //   shadowOffset: {
  //   height: 4,
  //   width: 3
  // }},

  breakfastBackground: {
    height: 250,
    width: 250,
    borderRadius: 7,
  },
  buttonContainer: {
    height: Responsive.height(45),
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    width: '90%',
    borderRadius: 5,
    margin: '5%',
    backgroundColor: 'transparent',
  },
  loginButton: {
    backgroundColor: '#000',
    shadowColor: '#808080',
    shadowOffset: {
      width: 0,
      height: 9,
    },
  },
  loginText: {
    color: 'white',
    fontSize: hp('1.6%'),
  },
  headerGoalText: {
    flexDirection: 'row',
    marginLeft: 5,
    color: '#000',
    fontSize: hp('2.2%'),
    marginBottom: 5,
    fontWeight: '500',
  },

  headerOverViewText: {
    marginLeft: 'auto',
    marginRight: Responsive.width(20),
    color: '#9E9F9D',
    fontSize: hp('1.6%'),
    marginBottom: 10,
    fontWeight: '500',
  },
  tipView: {
    padding: 12,
    marginHorizontal: 15,
    flexDirection: 'row',
    backgroundColor: 'rgba(0,0,0,0.05)',
    width: '92%',
    borderRadius: 7,
  },
  todayTrackingView: {
    width: '100%',
    borderRadius: 7,
  },
  trackOneStyle: {
    marginTop: '4%',
  },
  trackOneText: {
    flexDirection: 'row',
    marginLeft: 10,
    color: '#000',
    fontSize: hp('1.6%'),
    marginBottom: 3,
    fontWeight: '400',
  },
  trackOneStartText: {
    marginLeft: 'auto',
    marginRight: Responsive.width(5),
    color: '#000',
    fontSize: hp('1.6%'),
    marginBottom: 3,
    fontWeight: '600',
  },
  trackOneStartButtonText: {
    color: '#fff',
    fontSize: hp('1.2%'),
    fontWeight: '300',
    padding: 2,
  },
  dayButtonText: {
    color: '#fff',
    fontSize: hp('1.1%'),
    fontWeight: '300',
    padding: 2,
  },
  dayButton: {
    marginTop: Responsive.width(10),
    marginLeft: Responsive.width(5),
    height: Responsive.height(18),
    paddingLeft: Responsive.width(10),
    paddingRight: Responsive.width(10),
    backgroundColor: Colors.green,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: Responsive.height(5),
  },
  trackOneStartButton: {
    marginLeft: 'auto',
    marginRight: Responsive.width(5),
    height: Responsive.height(18),
    padding: 2,
    paddingLeft: Responsive.width(10),
    paddingRight: Responsive.width(10),
    backgroundColor: Colors.green,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: Responsive.height(5),
  },
  shortText: {
    marginLeft: Responsive.width(10),
    marginTop: Responsive.height(2),
    color: '#000',
    fontSize: hp('2.0%'),
    fontWeight: '400',
  },
  viewAllText: {
    marginTop: Responsive.height(2),
    marginLeft: 'auto',
    marginRight: Responsive.width(20),
    color: Colors.darkGrey,
    fontSize: hp('1.6%'),
    fontWeight: '500',
  },
  infoText: {
    marginLeft: Responsive.width(10),
    marginTop: Responsive.height(5),
    color: '#000',
    fontSize: hp('2.0%'),
    fontWeight: '400',
  },
  dailyCalText: {
    marginTop: Responsive.height(5),
    marginLeft: Responsive.width(10),
    color: '#000',
    fontSize: hp('1.6%'),
    fontWeight: '500',
  },
  feedsView: {
    marginTop: Responsive.height(1),
  },
  feedsViewBlog: {
    marginBottom: Responsive.height(30),
  },
  feedStyle: {
    marginTop: Responsive.height(10),
    width: '90%',
    height: Responsive.height(150),
    marginHorizontal: 20,
    backgroundColor: '#ffffff',
    shadowColor: '#D8D8D8',
    shadowOpacity: 1,
    shadowRadius: 2,
    borderRadius: 7,
    elevation: 5,
    borderColor: '#D8D8D8',
    shadowOffset: {
      height: 2,
      width: 1,
    },
  },
  keywords: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    flexWrap: 'wrap',
    textAlign: 'center',
    marginLeft: Responsive.width(15),
  },
  keyword: {
    fontSize: 14,
    color: '#000',
    backgroundColor: '#F3F3F3',
    padding: 5,
    marginLeft: Responsive.width(5),
    marginRight: Responsive.width(5),
  },
  keywordContainer: {},
  itemShortImage: {
    marginTop: Responsive.height(10),
    width: '90%',
    height: Responsive.height(150),
    marginHorizontal: 20,
    backgroundColor: '#ffffff',
    shadowColor: '#D8D8D8',
    shadowOpacity: 1,
    shadowRadius: 2,
    borderRadius: 12,
    elevation: 5,
    borderColor: '#D8D8D8',
    shadowOffset: {
      height: 2,
      width: 1,
    },
  },
  weeklyImage: {
    width: '98%',
    marginHorizontal: '2.5%',
    height: Responsive.height(220),
  },
  workoutImage: {
    marginTop: Responsive.height(10),
    width: '100%',
    height: Responsive.height(170),
    shadowColor: '#D8D8D8',
    shadowOpacity: 1,
    shadowRadius: 2,
    borderRadius: 20,
    elevation: 5,
    borderColor: '#D8D8D8',
    shadowOffset: {
      height: 2,
      width: 1,
    },
  },
  shadow: {
    shadowColor: '#ccc',
    shadowOpacity: 0.8,
    shadowRadius: 3,
    shadowOffset: {
      height: 5,
      width: 2,
    },
    elevation: 3,
  },
  button: {
    backgroundColor: '#B76EC6',
    opacity: 1,
    borderRadius: 10,
    alignSelf: 'stretch',
    justifyContent: 'center',
    alignItems: 'center',
  },
  markerContainer: {
    flexDirection: 'column',
    alignSelf: 'flex-start',
    zIndex: 999,
  },
  bubble: {
    flex: 1,
    flexWrap: 'wrap',

    backgroundColor: '#fff',

    width: 200,
    borderRadius: 3,
    borderColor: '#ccc',
    borderWidth: 0.5,
  },

  address: {
    color: '#9B9B9B',
    fontSize: 14,
  },
  hours: {
    color: '#4A4A4A',
    fontSize: 14,
  },
  arrow: {
    backgroundColor: 'transparent',
    borderWidth: 6,
    borderColor: 'transparent',
    borderTopColor: '#fff',
    alignSelf: 'center',
    marginTop: -9,
  },
  arrowBorder: {
    backgroundColor: 'transparent',
    borderWidth: 4,
    borderColor: 'transparent',
    borderTopColor: '#ccc',
    alignSelf: 'center',
    marginTop: -0.5,
  },
  panel: {
    flex: 1,
    backgroundColor: '#fff',
    paddingBottom: 40,
  },
  panelHeader: {
    height: 50,
    backgroundColor: '#eee',
    alignItems: 'center',
    justifyContent: 'center',
  },
  favoriteIcon: {
    position: 'absolute',
    top: -24,
    right: 24,
    backgroundColor: '#2b8a3e',
    width: 48,
    height: 48,
    padding: 8,
    borderRadius: 24,
    zIndex: 1,
  },

  mainViewStyle: {
    flex: 1,
    backgroundColor: '#fff',
  },
  rootContainer: {
    flexDirection: 'column',
    backgroundColor: 'white',
  },
  tabBar: {
    width: '100%',
    flexDirection: 'row',

    borderColor: 'rgba(0,0,0,0.3)',
    borderBottomWidth: Responsive.height(0.5),
  },
  tabTextWrapper: {
    marginTop: Responsive.height(15),
    paddingLeft: Responsive.width(35),
    paddingRight: Responsive.width(35),
    paddingBottom: Responsive.height(15),
    borderColor: '#7AD319',
  },
  tabText: {
    color: 'rgba(0,0,0,0.5)',
    fontSize: 16,
    fontFamily: 'helvetica',
  },
  container: {
    backgroundColor: 'transparent',
    height: '100%',
    width: '100%',
    flexDirection: 'column',
  },
  filterWrapper: {
    marginTop: Responsive.height(15),
    marginLeft: Responsive.width(20),
    flexDirection: 'row',
  },
  filterText: {
    color: 'rgba(122,211,25,1)',
    fontSize: 14,
    fontFamily: 'helvetica',
  },
  filterIcon: {
    marginLeft: Responsive.width(5),
    height: 16,
    width: 16,
  },
  multiJobsMsg: {
    marginTop: Responsive.height(13),
    color: 'black',
    opacity: 0.5,
    backgroundColor: 'transparent',
    fontSize: 11,
    textAlign: 'center',
    alignSelf: 'center',
    fontFamily: 'helvetica',
  },
  multiJobsMsgGreen: {
    color: 'white',
    marginTop: Responsive.height(13),
    marginBottom: Responsive.height(9),
    width: '100%',
    fontSize: 12,
    fontWeight: 'bold',
    textAlign: 'center',
    alignSelf: 'center',
    fontFamily: 'helvetica',
  },
  locationWrapper: {
    paddingTop: Responsive.height(15),
    paddingBottom: Responsive.height(15),
    paddingLeft: Responsive.width(23),
    paddingRight: Responsive.width(23),
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,1)',
  },
  locationText: {
    marginLeft: Responsive.width(3),
    color: 'rgba(122,211,25,1)',
    fontSize: 12,
    fontFamily: 'helvetica',
  },
  locationIcon: {
    height: Responsive.height(12),
    width: Responsive.height(12),
  },
  todoTaskCard: {
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    marginTop: 0,
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    borderRadius: Responsive.height(10),
    width: Responsive.width(328),
    overflow: 'hidden',
    elevation: Responsive.height(10),
  },
  taskInfo: {
    flexDirection: 'column',
    backgroundColor: '#f5f5f5',
    width: '100%',
    paddingTop: Responsive.height(13),
    paddingLeft: Responsive.width(15),
    paddingRight: Responsive.width(15),
  },
  taskBasicInfo: {
    flexDirection: 'row',
    width: '100%',
  },
  cardAvatar: {
    width: Responsive.height(44),
    height: Responsive.height(44),
    borderRadius: Responsive.height(5),
  },
  customerName: {
    color: 'rgba(0,0,0,1)',
    fontSize: 16,
    fontFamily: 'helvetica',
  },
  tagsBar: {
    flexDirection: 'row',
    marginTop: Responsive.height(10),
  },
  taskTags: {
    backgroundColor: 'rgba(122,211,25,1)',
  },
  taskPrice: {
    color: 'rgba(0,0,0,1)',
    fontSize: 18,
    fontWeight: 'bold',
    fontFamily: 'helvetica',
  },
  taskDistance: {
    color: 'rgba(0,0,0,0.5)',
    fontSize: 11,
    fontFamily: 'helvetica',
  },
  dateTimeLabel: {
    color: 'rgba(122,211,25,1)',
    fontSize: 10,
    fontFamily: 'helvetica',
  },
  dateTimeValue: {
    color: 'rgba(0,0,0,1)',
    fontSize: 12,
    fontFamily: 'helvetica',
  },
  pickupText: {
    left: '4%',
    marginTop: HEIGHT * 0.025,
    color: 'rgba(0,0,0,0.5)',
    fontSize: 11,
    fontFamily: 'helvetica',
  },
  addressText: {
    left: '4%',
    marginTop: '2%',
    color: 'rgba(0,0,0,1)',
    fontSize: 16,
    fontFamily: 'helvetica',
  },
  statusText: {
    color: 'rgba(0,0,0,0.5)',
    fontSize: 14,
    fontFamily: 'helvetica',
  },
  startJourney: {
    color: 'rgba(145,145,145,1)',
    fontSize: 16,
    fontFamily: 'helvetica',
  },
  startJourneyGreen: {
    color: 'white',
    fontSize: 16,
    fontFamily: 'helvetica',
    backgroundColor: APPLE_GREEN,
  },
  filterBackground: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0, 0.5)',
  },
  filterRoot: {
    marginTop: HEIGHT * 0.251,
    marginLeft: WIDTH * 0.131,
    height: Responsive.height(190),
    width: Responsive.width(300),
    borderRadius: 8,
    paddingTop: '2.65%',
    backgroundColor: 'white',
  },
  filterContainer: {
    backgroundColor: 'transparent',
    borderWidth: 0,
    padding: 0,
    margin: 0,
    marginLeft: Responsive.width(20),
    marginTop: Responsive.height(8),
  },
  filterCheckText: {
    fontSize: 12,
    textAlign: 'left',
    fontWeight: 'normal',
  },
  topBanner: {
    position: 'absolute',
    top: Responsive.height(24),
    width: '100%',
    marginHorizontal: Responsive.height(5),
    height: Responsive.height(20),
    flexDirection: 'row',
    color: 'white',
    backgroundColor: '#7AD319',
    alignItems: 'center',
  },
  ageContainer: {
    justifyContent: 'center',
    flex: 1,
    flexDirection: 'column',
  },

  goal1: {
    color: '#000',
    fontSize: 20,
    marginBottom: 2,
  },

  goal2: {
    margin: 10,
    marginLeft: 10,
    marginRight: 10,
    padding: 18,
    width: '90%',
    backgroundColor: '#ffffff',
    shadowColor: '#D8D8D8',
    shadowOpacity: 1,
    shadowRadius: 5,
    borderRadius: 7,
    elevation: 10,
    shadowOffset: {
      height: 5,
      width: 3,
    },
  },
  goal3: {
    width: '15%',
    height: '3%',
    marginLeft: 'auto',
    marginRight: '10%',
    backgroundColor: '#d9d9d9',
    shadowColor: '#000000',
    shadowOpacity: 1,
    shadowRadius: 2,
    shadowOffset: {
      height: 5,
      width: 3,
    },
  },
  goal4: {
    width: '15%',
    height: '10%',
    marginLeft: 'auto',
    marginRight: '10%',
    backgroundColor: '#d9d9d9',
    shadowColor: '#000000',
    shadowOpacity: 1,
    shadowRadius: 2,
    shadowOffset: {
      height: 5,
      width: 3,
    },
  },

  gendermain: {
    flexDirection: 'row',
    alignSelf: 'center',
    margin: 5,
  },
  textstyle: {
    textAlign: 'center',
    fontSize: 14,
    fontWeight: '700',
    color: 'black',
  },
  CalView: {
    width: wp(26),
    height: hp(3),
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  KLCstyle: {
    width: wp(20),
    height: hp(3),
    marginLeft: 10,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.green,
    borderRadius: 5,
  },
  gender: {
    marginHorizontal: 8,
    margin: 5,
    height: Responsive.height(100),
    width:
      Platform.OS === 'ios' ? Responsive.height(125) : Responsive.width(135),
  },

  TextInputStyle: {
    textAlign: 'center',
    height: '100%',
    color: '#000',
    // borderRadius: 10,
    // borderWidth: 2,
    flex: 1,
    fontSize: 80,
    // borderColor: '#009688',
  },
  heightTextInputStyle: {
    textAlign: 'center',
    height: '100%',
    color: '#000',
    marginLeft: '5%',
    // borderRadius: 10,
    // borderWidth: 2,
    fontSize: 60,
    // borderColor: '#009688',
  },
  headerSideText: {
    textAlign: 'center',
    marginTop: 'auto',
  },
  weightTextInputStyle: {
    textAlign: 'center',
    height: 60,
    color: '#000',
    // borderRadius: 10,
    // borderWidth: 2,
    flex: 1,
    fontSize: 50,
    // borderColor: '#009688',
  },
  targetWeightTextInputStyle: {
    textAlign: 'center',
    height: 60,
    color: '#000',
    // borderRadius: 10,
    // borderWidth: 2,
    flex: 1,
    fontSize: 50,
    // borderColor: '#009688',
  },
  heightbuttons: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 100,
    height: 40,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: '#D8D8D8',
  },
  borderRadiusLeft: {
    borderTopLeftRadius: 20,
    borderBottomLeftRadius: 20,
  },
  borderRadiusRight: {
    borderTopRightRadius: 20,
    borderBottomRightRadius: 20,
  },
  selectedbutton: {
    backgroundColor: '#fff',
  },
  snapsliderItemWrapper: {},
  snapsliderItem: {
    color: '#9E9F9D',
    fontSize: 12,
  },
  carouselContainer: {
    height: 200,
  },
  carousel: {
    flex: 1,
  },
});
