import { StyleSheet, Dimensions, Platform } from "react-native";

const { width, height } = Dimensions.get("window");
const WIDTH = Dimensions.get("window").width;
const HEIGHT = Dimensions.get("window").height;
const APPLE_GREEN = "#7AD319";

export const stylesActivity = StyleSheet.create({
  mainViewStyle: {
    flex: 1,
    backgroundColor: "#fff",
  },
  shadow: {
    shadowColor: "#ccc",
    shadowOpacity: 0.8,
    shadowRadius: 3,
    shadowOffset: {
      height: 5,
      width: 2,
    },
    elevation: 3,
  },
  button: {
    backgroundColor: "#B76EC6",
    opacity: 1,
    borderRadius: 10,
    alignSelf: "stretch",
    justifyContent: "center",
    alignItems: "center",
  },
  markerContainer: {
    flexDirection: "column",
    alignSelf: "flex-start",
    zIndex: 999,
  },
  bubble: {
    flex: 1,
    flexWrap: "wrap",

    backgroundColor: "#fff",

    width: 200,
    borderRadius: 3,
    borderColor: "#ccc",
    borderWidth: 0.5,
  },

  address: {
    color: "#9B9B9B",
    fontSize: 14,
  },
  hours: {
    color: "#4A4A4A",
    fontSize: 14,
  },
  arrow: {
    backgroundColor: "transparent",
    borderWidth: 6,
    borderColor: "transparent",
    borderTopColor: "#fff",
    alignSelf: "center",
    marginTop: -9,
  },
  arrowBorder: {
    backgroundColor: "transparent",
    borderWidth: 4,
    borderColor: "transparent",
    borderTopColor: "#ccc",
    alignSelf: "center",
    marginTop: -0.5,
  },
  panel: {
    flex: 1,
    backgroundColor: "#fff",
    paddingBottom: 40,
  },
  panelHeader: {
    height: 50,
    backgroundColor: "#eee",
    alignItems: "center",
    justifyContent: "center",
  },
  favoriteIcon: {
    position: "absolute",
    top: -24,
    right: 24,
    backgroundColor: "#2b8a3e",
    width: 48,
    height: 48,
    padding: 8,
    borderRadius: 24,
    zIndex: 1,
  },
  rootContainer: {
    flexDirection: "column",
    backgroundColor: "white",
  },
  tabBar: {
    width: "100%",
    flexDirection: "row",

    borderColor: "rgba(0,0,0,0.3)",
    borderBottomWidth: Responsive.height(0.5),
  },
  tabTextWrapper: {
    marginTop: Responsive.height(15),
    paddingLeft: Responsive.width(35),
    paddingRight: Responsive.width(35),
    paddingBottom: Responsive.height(15),
    borderColor: "#7AD319",
  },
  tabText: {
    color: "rgba(0,0,0,0.5)",
    fontSize: 16,
    fontFamily: "helvetica",
  },
  container: {
    backgroundColor: "transparent",
    height: "100%",
    width: "100%",
    flexDirection: "column",
  },
  filterWrapper: {
    marginTop: Responsive.height(15),
    marginLeft: Responsive.width(20),
    flexDirection: "row",
  },
  filterText: {
    color: "rgba(122,211,25,1)",
    fontSize: 14,
    fontFamily: "helvetica",
  },
  filterIcon: {
    marginLeft: Responsive.width(5),
    height: 16,
    width: 16,
  },
  multiJobsMsg: {
    marginTop: Responsive.height(13),
    color: "black",
    opacity: 0.5,
    backgroundColor: "transparent",
    fontSize: 11,
    textAlign: "center",
    alignSelf: "center",
    fontFamily: "helvetica",
  },
  multiJobsMsgGreen: {
    color: "white",
    marginTop: Responsive.height(13),
    marginBottom: Responsive.height(9),
    width: "100%",
    fontSize: 12,
    fontWeight: "bold",
    textAlign: "center",
    alignSelf: "center",
    fontFamily: "helvetica",
  },
  locationWrapper: {
    paddingTop: Responsive.height(15),
    paddingBottom: Responsive.height(15),
    paddingLeft: Responsive.width(23),
    paddingRight: Responsive.width(23),
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,1)",
  },
  locationText: {
    marginLeft: Responsive.width(3),
    color: "rgba(122,211,25,1)",
    fontSize: 12,
    fontFamily: "helvetica",
  },
  locationIcon: {
    height: Responsive.height(12),
    width: Responsive.height(12),
  },
  todoTaskCard: {
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    marginTop: 0,
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: Responsive.height(15),
    borderRadius: Responsive.height(10),
    width: Responsive.width(328),
    overflow: "hidden",
    elevation: Responsive.height(10),
  },
  taskInfo: {
    flexDirection: "column",
    backgroundColor: "#f5f5f5",
    width: "100%",
    paddingTop: Responsive.height(13),
    paddingLeft: Responsive.width(15),
    paddingRight: Responsive.width(15),
  },
  taskBasicInfo: {
    flexDirection: "row",
    width: "100%",
  },
  cardAvatar: {
    width: Responsive.height(44),
    height: Responsive.height(44),
    borderRadius: Responsive.height(5),
  },
  customerName: {
    color: "rgba(0,0,0,1)",
    fontSize: 16,
    fontFamily: "helvetica",
  },
  tagsBar: {
    flexDirection: "row",
    marginTop: Responsive.height(10),
  },
  taskTags: {
    backgroundColor: "rgba(122,211,25,1)",
  },
  taskPrice: {
    color: "rgba(0,0,0,1)",
    fontSize: 18,
    fontWeight: "bold",
    fontFamily: "helvetica",
  },
  taskDistance: {
    color: "rgba(0,0,0,0.5)",
    fontSize: 11,
    fontFamily: "helvetica",
  },
  dateTimeLabel: {
    color: "rgba(122,211,25,1)",
    fontSize: 10,
    fontFamily: "helvetica",
  },
  dateTimeValue: {
    color: "rgba(0,0,0,1)",
    fontSize: 12,
    fontFamily: "helvetica",
  },
  pickupText: {
    left: "4%",
    marginTop: HEIGHT * 0.025,
    color: "rgba(0,0,0,0.5)",
    fontSize: 11,
    fontFamily: "helvetica",
  },
  addressText: {
    left: "4%",
    marginTop: "2%",
    color: "rgba(0,0,0,1)",
    fontSize: 16,
    fontFamily: "helvetica",
  },
  statusText: {
    color: "rgba(0,0,0,0.5)",
    fontSize: 14,
    fontFamily: "helvetica",
  },
  startJourney: {
    color: "rgba(145,145,145,1)",
    fontSize: 16,
    fontFamily: "helvetica",
  },
  startJourneyGreen: {
    color: "white",
    fontSize: 16,
    fontFamily: "helvetica",
    backgroundColor: APPLE_GREEN,
  },
  filterBackground: {
    flex: 1,
    backgroundColor: "rgba(0,0,0, 0.5)",
  },
  filterRoot: {
    marginTop: HEIGHT * 0.251,
    marginLeft: WIDTH * 0.131,
    height: Responsive.height(190),
    width: Responsive.width(300),
    borderRadius: 8,
    paddingTop: "2.65%",
    backgroundColor: "white",
  },
  filterContainer: {
    backgroundColor: "transparent",
    borderWidth: 0,
    padding: 0,
    margin: 0,
    marginLeft: Responsive.width(20),
    marginTop: Responsive.height(8),
  },
  filterCheckText: {
    fontSize: 12,
    textAlign: "left",
    fontWeight: "normal",
  },
  topBanner: {
    position: "absolute",
    top: Responsive.height(24),
    width: "100%",
    marginHorizontal: Responsive.height(5),
    height: Responsive.height(20),
    flexDirection: "row",
    color: "white",
    backgroundColor: "#7AD319",
    alignItems: "center",
  },

  container: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#ffffff",
    flex: 1,
    flexDirection: "column",
  },
  ageContainer: {
    justifyContent: "center",
    flex: 1,
    flexDirection: "column",
  },

  goal1: {
    color: "#000",
    fontSize: 20,
    marginBottom: 2,
  },

  goal2: {
    margin: 10,
    marginLeft: 10,
    marginRight: 10,
    padding: 18,
    width: "90%",
    backgroundColor: "#ffffff",
    shadowColor: "#D8D8D8",
    shadowOpacity: 1,
    shadowRadius: 5,
    borderRadius: 7,
    elevation: 10,
    shadowOffset: {
      height: 5,
      width: 3,
    },
  },
  goal3: {
    width: "15%",
    height: "3%",
    marginLeft: "auto",
    marginRight: "10%",
    backgroundColor: "#d9d9d9",
    shadowColor: "#000000",
    shadowOpacity: 1,
    shadowRadius: 2,
    shadowOffset: {
      height: 5,
      width: 3,
    },
  },
  goal4: {
    width: "15%",
    height: "10%",
    marginLeft: "auto",
    marginRight: "10%",
    backgroundColor: "#d9d9d9",
    shadowColor: "#000000",
    shadowOpacity: 1,
    shadowRadius: 2,
    shadowOffset: {
      height: 5,
      width: 3,
    },
  },

  gendermain: {
    flexDirection: "row",
  },
  gender: {
    marginHorizontal: 10,
    margin: 8,
    height: 120,
    width: 120,
    alignItems: "center",
    padding: 8,
    backgroundColor: "#ffffff",
    shadowColor: "#D8D8D8",
    shadowOpacity: 1,
    shadowRadius: 5,
    borderRadius: 7,
    elevation: 10,
    borderStyle: "solid",
    borderWidth: 1,
    borderColor: "#D8D8D8",
    shadowOffset: {
      height: 4,
      width: 3,
    },
  },
  headerText: {
    fontSize: 20,
    textAlign: "center",
    margin: 10,
    fontWeight: "bold",
  },
  TextInputStyle: {
    textAlign: "center",
    height: "100%",
    color: "#000",
    // borderRadius: 10,
    // borderWidth: 2,
    flex: 1,
    fontSize: 80,
    // borderColor: '#009688',
  },
  heightTextInputStyle: {
    textAlign: "center",
    height: "100%",
    color: "#000",
    marginLeft: "5%",
    // borderRadius: 10,
    // borderWidth: 2,
    fontSize: 60,
    // borderColor: '#009688',
  },
  headerSideText: {
    textAlign: "center",
    marginTop: "auto",
  },
  weightTextInputStyle: {
    textAlign: "center",
    height: 60,
    color: "#000",
    // borderRadius: 10,
    // borderWidth: 2,
    flex: 1,
    fontSize: 50,
    // borderColor: '#009688',
  },
  targetWeightTextInputStyle: {
    textAlign: "center",
    height: 60,
    color: "#000",
    // borderRadius: 10,
    // borderWidth: 2,
    flex: 1,
    fontSize: 50,
    // borderColor: '#009688',
  },
  heightbuttons: {
    justifyContent: "center",
    alignItems: "center",
    width: 100,
    height: 40,
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: "#D8D8D8",
  },
  borderRadiusLeft: {
    borderTopLeftRadius: 20,
    borderBottomLeftRadius: 20,
  },
  borderRadiusRight: {
    borderTopRightRadius: 20,
    borderBottomRightRadius: 20,
  },
  selectedbutton: {
    backgroundColor: "#fff",
  },
  snapsliderContainer: {
    color: "white",
  },
  snapslider: {},
  snapsliderItemWrapper: {},
  snapsliderItem: {
    color: "#9E9F9D",
    fontSize: 12,
  },
  carouselContainer: {
    height: 200,
  },
  carousel: {
    flex: 1,
  },
});
