export const SESSION_STATUS = 'SESSION_STATUS'
export const SESSION_KEY = 'SESSION_KEY'
export const USER_DATA = 'USER_DATA'
export const USER_DATA_NAME = 'USER_DATA_NAME'
export const USER_SIGNUP_CHECK = 'USER_SIGNUP_CHECK'
export const USER_DATA_ID = 'USER_DATA_ID'
export const LANGUAGE_TRANSLATE = 'LANGUAGE_TRANSLATE'

