export const SESSION_STATUS = 'SESSION_STATUS'
export const SESSION_KEY = 'SESSION_KEY'
export const USER_DATA = 'USER_DATA'
export const UPDATE_GOAL = 'UPDATE_GOAL'
export const UPDATE_PHYSICAL_ACTIVITY = 'UPDATE_PHYSICAL_ACTIVITY'
export const UPDATE_GENDER = 'UPDATE_GENDER'
export const UPDATE_PROFILE_STATUS = 'UPDATE_PROFILE_STATUS'
export const UPDATE_AGE = 'UPDATE_AGE'
export const UPDATE_WEIGHT = 'UPDATE_WEIGHT'
export const UPDATE_HEIGHT = 'UPDATE_HEIGHT'
export const UPDATE_CURRENTFAT = 'UPDATE_CURRENTFAT'
export const UPDATE_TARGETWEIGHT = 'UPDATE_TARGETWEIGHT'
export const UPDATE_LEVEL = 'UPDATE_LEVEL'
export const UPDATE_USERSTATUS = 'UPDATE_USERSTATUS'
export const UPDATE_USERDETAIL = 'UPDATE_USERDETAIL'
export const UPDATE_RECIPE = 'UPDATE_RECIPE'


export const UPDATE_USER_GENDER = 'UPDATE_USER_GENDER'
export const UPDATE_USER_AGE = 'UPDATE_USER_AGE'
export const UPDATE_USER_WEIGHT = 'UPDATE_USER_WEIGHT'
export const UPDATE_USER_HEIGHT = 'UPDATE_USER_HEIGHT'
export const UPDATE_USER_EBF= 'UPDATE_USER_EBF'
export const UPDATE_USER_BMI = 'UPDATE_USER_BMI'
export const UPDATE_USER_ACTIVITYLEVEL = 'UPDATE_USER_ACTIVITYLEVEL'
export const UPDATE_USER_TOTALDAILYKCAL = 'UPDATE_USER_TOTALDAILYKCAL'
export const UPDATE_USER_TOTALWEEKLYKCAL = 'UPDATE_USER_TOTALWEEKLYKCAL'
export const UPDATE_USER_ACTIVITIES = 'UPDATE_USER_ACTIVITIES'

export const UPDATE_SPLASHSTATUS = 'UPDATE_SPLASHSTATUS'
export const UPDATE_USERFEATURESTATUS = 'UPDATE_USERFEATURESTATUS'
export const UPDATE_HOMESTATUS = 'UPDATE_HOMESTATUS'
export const REMAINING_CALORIES = 'REMAINING_CALORIES'





