export const ROUTE_NAME = 'ROUTE_NAME';
export const CURRENT_ORDER = 'CURRENT_ORDER';
export const NAVIGATION = 'NAVIGATION';
export const CURRENT_ORDER_REQUESTS = 'CURRENT_ORDER_REQUESTS';
export const TODAY_POST_SHOW = 'TODAY_POST_SHOW';
export const TODAY_MEAL_SHOW = 'TODAY_POST_SHOW';

export const ADD_UPDATE_ACTIVITIES = 'ADD_UPDATE_ACTIVITIES';
export const ALL_LIST_ACTIVITIES = 'ALL_LIST_ACTIVITIES';

export const RECIPES_LIST_SHOW = 'RECIPES_LIST_SHOW';
export const RECIPES_LIST_CHECK = 'RECIPES_LIST_CHECK';
