export const ROUTE_NAME = 'ROUTE_NAME';
export const CURRENT_ORDER = 'CURRENT_ORDER';
export const NAVIGATION = 'NAVIGATION';
export const CURRENT_ORDER_REQUESTS = 'CURRENT_ORDER_REQUESTS';
export const BLOG_LIST_SHOW = 'BLOG_LIST_SHOW';
export const TODAY_POST_SHOW = 'TODAY_POST_SHOW';
export const TODAY_MEAL_SHOW = 'TODAY_POST_SHOW';

export const USER_SUBSCRIPTION = 'USER_SUBSCRIPTION';
